api:
  environment: local
  upload-signature-duration-in-minutes: 10
  main-bucket-name: main-media-storage
  sandbox-bucket-name: sandbox-media-storage
  minio:
    endpoint: http://localhost:9000
    accesskey: accesskey
    secretkey: secretkey
